### ISSUE TITLE
Confirm all the data, add fields that are missing, API's, etc.

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#101]
# All the fields

Issuers have Programs, Programs have Badges.
Badges can count towards earning other Badges. Some badges can only be earned by earning prerequisite Badges. Badges can count towards the earning of another Badge in specific numbers, so a single Badge can count as 2 points toward another Badge, or 1 point, or zero...etc.
## Organization / Issuer
- [x] Issuer Name
- [ ] Issuer Description - _mockups don't show this anywhere_
- [ ] Issuer Logo - _mockups don't show this anywhere_
- [x] Issuer URL
## Program
- [x] Program Name
- [x] Program Description
- [x] Begin Date
- [x] End Date
- [x] Program site, a url where more information lives.
- [x] Program Logo
- [x] Phone Number - _mockups don't show this anywhere_
- [x] Contact - _mockups don't show this anywhere_
## Badge
- [x] Badge Name
- [x] Badge Description
- [x] Badge Criteria
- [ ] Badge Category
- [x] Tags
- [ ] Time to earn (how long will it take to earn this badge? 1-4 hours, 1 day, 1 week)
- [ ] Age Range (<13, 13-18, 19-24)
- [ ] Does this badge have prerequisites?
- [ ] Does this badge count towards another badge? Which badge? How much does it count against that badge?
- [ ] Badge type (enumerated list : self-paced, in person, etc)

TODO
- [ ] Add the fields to the models
- [ ] Add the fields to the admin panel
- [ ] Add the fields to API

**Comment by cmcavoy** [comment]
@iamjessklein there's a few fields above that aren't in the mockups...can you confirm? If we don't need them, we won't add or collect them. /cc @threeqube

**Comment by threeqube** [comment]
We need all of them. @iamjessklein we can discuss but we should make sure the above fields are incorporated.

**Comment by brianloveswords** [comment]
@cmcavoy For the things that say "mockups don't show this anywhere", should I hold off on implementing those?

**Comment by cmcavoy** [comment]
No - @threeqube confirmed that they're all necessary. If the mockups don't
show them, we're asking @iamjessklein to add them.

On Mon, May 20, 2013 at 2:03 PM, Brian J Brennan
notifications@github.comwrote:

> @cmcavoy https://github.com/cmcavoy For the things that say "mockups
> don't show this anywhere", should I hold off on implementing those?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/101#issuecomment-18165792
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by brianloveswords** [comment]
@cmcavoy What is the "badge category"? Does that mean "science", "technology", "math", etc?

**Comment by brianloveswords** [comment]
@cmcavoy Is badge "time to earn" a dropdown list with just those three options?

**Comment by cmcavoy** [comment]
> @cmcavoy What is the "badge category"? Does that mean "science", "technology", "math", etc?

@brianloveswords yes, so replace it with whatever is appropriate for the related steam category / auto-award work.

**Comment by cmcavoy** [comment]
> @cmcavoy Is badge "time to earn" a dropdown list with just those three options?

Yes, for now. Might add more options, but for now - yes. For sure options rather than free-form.

**Comment by brianloveswords** [comment]
> Badge type (enumerated list : self-paced, in person, etc)

What are the rest of the items in the list?

**Comment by cmcavoy** [comment]
> What are the rest of the items in the list?

There's three, "self-paced activity", "activity" and "participation".

@threeqube @carlacasilli can confirm for sure. The key one to track is self-paced v. the other two. Self-paced will be presented differently in the interface and will use Aestimia for submissions. /cc @stenington and @andrewhayward as they're working on the other side that will consume this field.

**Comment by threeqube** [comment]
Sorry coming to this late. 

Badge type is actually as follows: Participation, Skill, Achievement

Activity type: online or offline

Badge topic: S, T, E, A, or M

Time to learn, I'm not sure how best to handle as a drop down. We decided not to include this as a filter because the data normalization might get too hairy. @carlacasilli may be able to provide drop down suggestions.

**Comment by threeqube** [comment]
@cmcavoy this is for Camri but activity type (online or offline) is not specifically called out on the spreadsheet but but that information needs to be input when we input all the badges. @carlacasilli and I can talk Camri through on which ones are online and which are offline.
