### ISSUE TITLE
Add frontend connections for `categoryAward`, `categoryRequirement` and `categoryWeight`

### ISSUE THREAD

**Issue by brianloveswords** [mozilla/openbadger#126]
This is for the big category, city-wide badges (i.e., "Science badge", "Technology badge").
- `categoryAward` is whether or not a badge should be considered one of these city badges (there will only be five badges that should have this be `true`)
- `categoryRequirement` is the "score" needed for a category badge to be auto-awarded (as far as I know, this will almost always be 3 for CSOL)
- `categoryWeight` is the amount that a non-category badge counts towards the relevant category badge.

The logic is already in the backend and the model, we just need to add the relevant inputs to the frontend (`create-or-edit-badge.html`, I believe) and the route handler (`routes/badge.js`).

@cmcavoy, feel free to clarify anything if I've gotten anything wrong.

**Comment by threeqube** [comment]
Logic here fyi: https://github.com/mozilla/openbadger/issues/90#issuecomment-17913973
