### ISSUE TITLE
Enable orgs to generate claim codes themselves

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#127]
Currently, we need to generate claim codes for the orgs who need them to issue paper claim code badges. We should automate this for the orgs so they can create the codes themselves whenever they need them.

**Comment by cmcavoy** [comment]
not for June 1, but yes...agreed.

**Comment by threeqube** [comment]
:+1:

**Comment by toolness** [comment]
Is this just a permissions thing?  e.g. allowing anyone who is classified as an org member to be able to access and use the claim code management page?

**Comment by threeqube** [comment]
Currently the way we have the system set up, the orgs send us a list of emails of all the instructors that should have admin privileges and we (I) input them through Open Badger. Those folks will have access to use the claim code management page. cc/ @cmcavoy

**Comment by toolness** [comment]
Oh, so is this the same thing as #219 then?

**Comment by threeqube** [comment]
Oh yeah same issue indeed. I'll close this.
