### ISSUE TITLE
Copy for CSOL issue non-claim code badges landing page

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#129]
Relevant workflow can be found here: https://github.com/mozilla/openbadger/issues/78#issuecomment-18497848

Specific page is here:

![landing-page](https://f.cloud.github.com/assets/535012/487854/346c92c8-b96b-11e2-928f-835a2f21589d.png)

**Comment by cmcavoy** [comment]
Not sure this is right. When someone signs into OpenBadger, they're 'detected' as an admin or an issuer. If they're an admin, they get the admin panel, if they're an issuer, they get the issue badges panel. We won't be able to separate out the copy until we know who they are.

If you go to the [staging site](http://openbadger-csol.mofostaging.net/) you can see where we're at currently, and suggest copy replacements (we still have webmaker language in there).

**Comment by threeqube** [comment]
Ah, you're right. I will close this and issue the correct tickets accordingly.
