### ISSUE TITLE
Implement copy for CSOL issue non-claim code badges badge award text for learner

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#134]
Copy here: https://github.com/mozilla/openbadger/issues/133

**Comment by emgollie** [comment]
@cmcavoy, do we want to assign this or are you on the case? Gracias.

**Comment by threeqube** [comment]
@cmcavoy are we doing the "new" label? If we're not, then this isn't in scope and we can close it I think.

**Comment by cmcavoy** [comment]
AFAIK we're not doing the new label.

On Fri, Jun 7, 2013 at 5:12 AM, threeqube notifications@github.com wrote:

> @cmcavoy https://github.com/cmcavoy are we doing the "new" label? If
> we're not, then this isn't in scope and we can close it I think.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/134#issuecomment-19098993
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by threeqube** [comment]
So we won't have this "Hippity hop! You just earned this badge!" text. Closing.
