### ISSUE TITLE
BLOCKER: Change some fields to not-required

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#140]
This is a blocker for data entry, the following fields need to be marked as not-required
- [x] program contact
- [x] issuer contact
- [x] issuer image

**Comment by toolness** [comment]
It appears to already be the case that program contacts aren't required... Let me know if I'm wrong about this, but I just tried making a new program on my local instance, without providing the contact or the phone number, and it seemed to work fine.

**Comment by toolness** [comment]
Hmm, it also seems to be the case that issuer image isn't required, either. I'm able to create new issuers without having to specify an image on Firefox. So, marking this ticket as done... if any of the sub-parts are still not working for you, please open separate bugs for them. Thanks!
