### ISSUE TITLE
Update time to complete field

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#149]
1 - 24 hours
1 - 6 days
1 - 4 weeks
1 - 3 months
more than 3 months

**Comment by brianloveswords** [comment]
Just an idea: Could this possible be simplified by doing "hours", "days", "weeks", "months", "longer"?

**Comment by cmcavoy** [comment]
pro-move. let's do that.

On Wed, May 29, 2013 at 11:11 AM, Brian J Brennan
notifications@github.comwrote:

> Just an idea: Could this possible be simplified by doing "hours", "days",
> "weeks", "months", "longer"?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/149#issuecomment-18627710
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by toolness** [comment]
Cool. Internally in the DB we can call these whatever we want... currently it's "short", "medium", and "long", even though the text the users see is different.

I was thinking that since there are now 5 categories instead of 3, we could do **short**, **medium**, **long**, **epic**, and **legendary**, but I suppose we can just store things internally as their actual names, since they are nice and short too.

Well, unless we've already got data entered using the old schema... do we?  In that case, I recommend just adding epic and legendary.

**Comment by cmcavoy** [comment]
There's some data entered under the old schema, but it's easy enough to
correct. I'd rather store the 5 fields in more obvious form. like, which is
longer...epic...or legendary? It's not obvious...i mean...unless you're jrr
tolkien.

On Wed, May 29, 2013 at 12:55 PM, Atul Varma notifications@github.comwrote:

> Cool. Internally in the DB we can call these whatever we want... currently
> it's "short", "medium", and "long", even though the text the users see is
> different.
> 
> I was thinking that since there are now 5 categories instead of 3, we
> could do _short_, _medium_, _long_, _epic_, and _legendary_, but I
> suppose we can just store things internally as their actual names, since
> they are nice and short too.
> 
> Well, unless we've already got data entered using the old schema... do we?
> In that case, I recommend just adding epic and legendary.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/149#issuecomment-18634371
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by toolness** [comment]
or you play World of Warcraft.

**Comment by cmcavoy** [comment]
:thumbsup: to time-based words (day, week, etc...) ;)

On Wed, May 29, 2013 at 12:59 PM, Atul Varma notifications@github.comwrote:

> or you play World of Warcraft.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/149#issuecomment-18634647
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by toolness** [comment]
Cool. I also mentioned in the commit log:

> Internally we store 'longer' as 'years', since this makes more sense in isolation (e.g. if someone just sees 'longer' w/o seeing 'months' before it, they'll wonder what it's longer than).

If you disagree, let me know and I'll change the internal representation to "longer" too.

**Comment by cmcavoy** [comment]
We have a handful that are "1 year". I'm ok with 'years' in the db.

On Wed, May 29, 2013 at 1:05 PM, Atul Varma notifications@github.comwrote:

> Cool. I also mentioned in the commit log:
> 
> Internally we store 'longer' as 'years', since this makes more sense in
> isolation (e.g. if someone just sees 'longer' w/o seeing 'months' before
> it, they'll wonder what it's longer than).
> 
> If you disagree, let me know and I'll change the internal representation
> to "longer" too.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/149#issuecomment-18635003
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com
