### ISSUE TITLE
Generate JWT key for iRemix on staging

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#150]
email it to chris@mozillafoundation.org

they need to start integration work with iRemix, they need a key so they can make authenticated calls.

**Comment by toolness** [comment]
Is this something JP can do?  It's just an environment variable, `OPENBADGER_JWT_SECRET`, that needs to be set to something secret. I don't know where the staging/prod machines are, so I'm not sure how to do it myself...

**Comment by cmcavoy** [comment]
you're totally right, I thought it was more complicated. I'm on it.

On Wed, May 29, 2013 at 12:26 PM, Atul Varma notifications@github.comwrote:

> Is this something JP can do? It's just an environment variable,
> OPENBADGER_JWT_SECRET, that needs to be set to something secret. I don't
> know where the staging/prod machines are, so I'm not sure how to do it
> myself...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/150#issuecomment-18632451
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com
