### ISSUE TITLE
Need a delete button in the admin interface

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#158]
to delete badges. no delete button for programs and issuers yet, as I don't know if it should cascade or what.

**Comment by toolness** [comment]
Ok... I assume this should cascade down to all instances of the badge too, right?

**Comment by cmcavoy** [comment]
If there's instances of the badge, then don't allow them to delete.

The use case here is Camri needs to delete test badge definitions. We could do it by hand if we need to.

**Comment by toolness** [comment]
Ohhh got it.
