### ISSUE TITLE
Move wiki/APIv2 into the code repository?

### ISSUE THREAD

**Issue by toolness** [mozilla/openbadger#160]
I'm wondering if we should move the spec at [wiki/APIv2](https://github.com/mozilla/openbadger/wiki/APIv2) into the repository, say, into a `docs/api.md` file. Github's default view for Markdown files would make the spec just as easy to view on the web (see e.g. [this example](https://github.com/mozilla/openbadger/blob/v2.0/README.md)), but it'd tie every version of the spec to a specific version of the implementation, allowing us to easily see an accurate spec given a specific implementation. This would be particularly nice for pull requests involving tentative API changes and such. It'd also encourage us to keep the spec up to date, as it's closer to where the implementation lives.

Thoughts, @stenington and @brianloveswords?

**Comment by stenington** [comment]
Makes a ton of sense to me. I think the wiki doc is useful as an API wishlist, but having docs that represent reality would be really nice.
