### ISSUE TITLE
Wrong issuer url in assertion

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadger#161]
I think [this line](https://github.com/mozilla/openbadger/blob/v2.0/models/program.js#L80) provides the wrong url for an assertion. I believe it needs to be the base url of the openbadger instance to be OBI-compliant. Right @brianloveswords?

**Comment by brianloveswords** [comment]
@stenington It does not – https://github.com/mozilla/openbadges/wiki/Assertions#issuerorganization, URL should point to the URL of the issuing organization. There used to be a concept of `origin`, which would have been required to be the openbadger url, but that was scrapped for 1.0.
