### ISSUE TITLE
Need program and issuer information along with badge data through API

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadger#162]
It would be awesome if the `/v2/badge/:shortname` and `/v2/user/badge/:shortname` endpoints returned badge data with fully inflated program and issuer data. Several CSOL screens want to link between those elements, and making several API calls is annoying.

**Comment by stenington** [comment]
Basically instead of `"program": <shortname>` it would be nice to inflate that shortname to the same thing returned by [`/v2/program/:shortname`](https://github.com/mozilla/openbadger/wiki/APIv2#get-v2programshortname).

**Comment by toolness** [comment]
Hmm, I think that makes sense when we're delivering only one badge, which we are in the endpoints you mentioned. But for cases where we return lots of badges, is it ok to just keep returning the shortname of the program? Otherwise the denormalized data could get massively big for lots of badges.

**Comment by stenington** [comment]
Yeah, I think that's fine for CSOL purposes, certainly.
