### ISSUE TITLE
Add recommend based on badge to endpoint

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#165]
Related to #86 but more about immediate things we need to use the recommendations on CSOL at all. In addition to [recommendations based on user](https://github.com/mozilla/openbadger/blob/v2.0/docs/api.md#get-v2userrecommendations) we need an endpoint that returns similar badges if passed a specific badge.

Probably something like `GET /v2/badge/<shortname>/similar` that returns ~5-10 badges in the same category. We can tweak after that basic call works.

**Comment by cmcavoy** [comment]
@brianloveswords assigned, this is a biggish blocker, fyi.

**Comment by brianloveswords** [comment]
I just noticed – this ticket says "category", and the original implementation/ticket said "tags". Should it be tags or categories?

**Comment by cmcavoy** [comment]
Category...tags is sadly under-utilized right now.

On Sun, Jun 2, 2013 at 11:41 AM, Brian J Brennan
notifications@github.comwrote:

> I just noticed – this ticket says "category", and the original
> implementation/ticket said "tags". Should it be tags or categories?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/165#issuecomment-18809159
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by brianloveswords** [comment]
Closed by #170
