### ISSUE TITLE
Program(s) API endpoint doesn't include `issuer` information

### ISSUE THREAD

**Issue by andrewhayward** [mozilla/openbadger#167]
[The docs](https://github.com/mozilla/openbadger/blob/v2.0/docs/api.md#get-v2programshortname) say that the `program` endpoint should include `issuer` information, but that doesn't seem to be the case.

Equally, [the `programs` endpoint docs](https://github.com/mozilla/openbadger/blob/v2.0/docs/api.md#get-v2programs) don't mention anything about issuers, but might be useful to include them here too.

**Comment by andrewhayward** [comment]
Also, where the docs do mention `issuer`s, it doesn't say anything about `shortname`s, which would be useful information to have.

**Comment by toolness** [comment]
Hmm, I thought I fixed your first concern in 74a399b44358b9ec3df30994b1d906d3eeb3ad96. Are you using the latest master branch?

**Comment by toolness** [comment]
Ah, good point about the shortnames...

**Comment by andrewhayward** [comment]
I'm using whatever's deployed on staging, which may or may not be up-to-date.

**Comment by toolness** [comment]
Ah, I think that it wasn't up to date, so I'm closing this bug! Feel free to reopen though.
