### ISSUE TITLE
Add age ranges to program list

### ISSUE THREAD

**Issue by andrewhayward** [mozilla/openbadger#168]
Programs don't currently carry age range information. This appears to be data owned by individual badges, but a list of ranges based on that would be good to have.

**Comment by brianloveswords** [comment]
What API endpoint should this eventually work its way into?

**Comment by andrewhayward** [comment]
@brianloveswords - we need it in `/v2/programs` to filter the data. Could go in `/v2/program/<shortname>` too, potentially.
