### ISSUE TITLE
Add an API endpoint for user → badge recommendations

### ISSUE THREAD

**Issue by brianloveswords** [mozilla/openbadger#172]
**Endpoint**: `/v2/user/recommendations`
**Options**: 
- **email**: User email address. Used to filter out existing badges.
- **limit**: How many badges to return. Default to `10`, pass `0` for unlimited
- **ageRange** (?) : User's age range. See "Slightly Smarter Strategy" below.

**Easy, Dumb Strategy**: Get all categories of badges a user has and return badges with the same categories. Note, this could include the entire set of badges, so randomize the list before returning. For users without any badges, this will be worthless.

**Slightly Smarter Strategy**: Get all badges for the user's age range. ( **Does CSOL know the user's age range?** ). This will be more useful for brand new users.

@cmcavoy, any thoughts on which of these to pursue? I welcome any alternative strategies as well.

**Comment by brianloveswords** [comment]
Proposed rules from @erinknight with my effort estimates inline:

Implicit: filter out the city level badges from the recommendation results.

# 

> It shouldn't recommend badges that you've already earned. 

Easy 

# 

> It should only recommend badges appropriate for your age range (<13 or >13+)

Easy, so long as that information is passed in by CSOL when making an API request. @cmcavoy, **will it be passed in as one of the ranges we specify in openbadger or an exact age?** Exact age will be slightly harder, but not terrible.

# 

> It should bias towards the online self-paced activities since we want to suggest badges that someone could get right now or at all (some programs are already full or closed). 

**Problem:** We don't have the concept of "self-paced" activities in openbadger. We have badge type (`skill`, `achievement`, and `participation`) and activity type (`offline` and `online`).

If you just mean `online`, should not be too hard, depending on what you mean by "bias". It's easier to _only_ show online badges, but not too much harder to show online badges first, then offline afterwards.

# 

> If showing any badges from programs at all, those should only be badges from programs that haven't occurred yet. So there needs to be a date constraint - even better if it biased towards things that were happening today or soon. But that's a nice to have. 

This criteria confuses me a bit. As far as I know **all** badges are associated with programs. If a program hasn't happened yet, can the earner still get the badge? Should it only recommend badges where today's date is between the start and end date of the program (inclusive)?

# 

> If you just earned an S badge, and are thus on the Science track, it should show you other S badges you could get to fulfill the city-level badge requirement. So drive people towards the city level badge in the category that they are in. Again, biasing towards the online self-paced activities.

Every badge (except the `participation` badges) contribute towards the city badges (which we just call `categoryBadges` in openbadger since they are all based on categories). So I think this is saying "filter out all `participation` badges"), which is easy.

# 

> If the badge you just earned is cross listed (S and T), then you are on two tracks, Science and Technology. Ideally we can show recommendations for both, but this probably needs Jess brought back in. 

It's slightly harder to _not_ show badges from both tracks (implementation was going to take into account all of the badges the user has earned, not just the latest, so at some point most earners will be on all five tracks).

# 

> Once you've earned the city level badge in a particular category, that track is closed. If you have other tracks open, continue to recommend in those tracks.

Find all the user's city badges and run a filter against the recommendations based on the `category` of the earned city badges (since they all always belong to a single category). Should be easy.

# 

> If no current tracks open, it should suggest badges from the other categories that you haven't done or received a badge in until you have a badge that puts into a new track for a city level badge
> 
> If you have all of the city level badges, the just show a random set of badges 

Implementation wise, I think this is saying "if after all the filters have been applied, if there are no badges left, recommend a randomized list of unearned badges with no other filters, biasing towards `online`, non-`participation` badges"

**Comment by erinknight** [comment]
Thanks @brianloveswords - looks good. Comments on a few specific ones below:

> > It should only recommend badges appropriate for your age range (13+)
> 
> Easy, so long as that information is passed in by CSOL when making an API request. @cmcavoy, will it be passed in as one of the ranges we specify in openbadger or an exact age? Exact age will be slightly harder, but not terrible.

The date ranges we had for the badges are <13, 13-18 and 19-24. When the kids sign up, we collect DOB. But the under 13, 13 and older distinction is fine I think.

> > It should bias towards the online self-paced activities since we want to suggest badges that someone could get right now or at all (some programs are already full or closed).
> 
> Problem: We don't have the concept of "self-paced" activities in openbadger. We have badge type (skill, achievement, and participation) and activity type (offline and online).
> If you just mean online, should not be too hard, depending on what you mean by "bias". It's easier to only show online badges, but not too much harder to show online badges first, then offline afterwards.

I do mean online. Probably okay to just recommend online, but better if its online first and some offline.

> > If showing any badges from programs at all, those should only be badges from programs that haven't occurred yet. So there needs to be a date constraint - even better if it biased towards things that were happening today or soon. But that's a nice to have.
> 
> This criteria confuses me a bit. As far as I know all badges are associated with programs. If a program hasn't happened yet, can the earner still get the badge? Should it only recommend badges where today's date is between the start and end date of the program (inclusive)?

So I didn't think the online activities were associated with a program. Just found out that they are all associated with DYN. So when I say 'if showing any badges from programs' I mean 'if showing offline badges'. For the offline badges, I think its only showing the badges for programs with start dates after today.

> > If the badge you just earned is cross listed (S and T), then you are on two tracks, Science and Technology. Ideally we can show recommendations for both, but this probably needs Jess brought back in.
> 
> It's slightly harder to not show badges from both tracks (implementation was going to take into account all of the badges the user has earned, not just the latest, so at some point most earners will be on all five tracks).

So this might be mostly an @iamjessklein thing. But we need some way visually that the recommendation system is driving you towards particular goals. So if you are in all 5 tracks and all the recommended badges are lumped together, then you don't really have any clear pathways. Like I said in the email, I just made up the track idea today - open to other suggestions on how we can handle/present this.

**Comment by carlacasilli** [comment]
Hey, the track concept is great. If we can keep track of what someone has earned the most of and continue to suggest badges that align with those, that's optimal. 

What I previously mentioned in another ticket was the following equation.

Optimal:
You've earned two skill badges, one in Science, Technology, Engineering, Math, and one in Science, Technology. Show 1 Science Badge, 1 Technology Badge. For the remaining badges, show any combo of Science, Technology, Engineering or Math.

Alternative:
If you have just earned a skill badge covering Technology and Art then you'd be shown 1 badge each for Technology and Art (recognizing that most badges cross multiple categories) and the remaining 3 would be any random assortment of S, T, E, A, or M.

**Comment by iamjessklein** [comment]
@chloeatplay is working on the UX for this concept here: https://github.com/mozilla/CSOL-site/issues/382

**Comment by brianloveswords** [comment]
This is done
