### ISSUE TITLE
Login via Email on http://openbadger-csol.mofostaging.net/ via Persona throws Forbidden

### ISSUE THREAD

**Issue by mark-ellul** [mozilla/openbadger#178]
Hi,

I am trying to log into http://openbadger-csol.mofostaging.net/ via Email (Persona) and when it returns back to the site, I get a forbidden error

http://monosnap.com/image/Nap3UOBkwjAAMLRTyQeaxmRq7

Not sure if its supposed to work or not...

**Comment by brianloveswords** [comment]
@mark-ellul I think this is expected behavior, though the messaging could be clearer. In order to log in to the admin section, your email needs to be on the admin list.
