### ISSUE TITLE
Add a "print claim codes" option for issuers

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#184]
Similar to your text download, but with a little bit of flair.

If you can build a view of the available claim codes that includes a picture of the badge and a description of what you need to do to claim the badge (/cc @iamjessklein ) so that someone at the library can print out 10 claim code sheets.

Something to note:
1. These should be new claim codes, and should be marked as "distributed". Date of the creation should be tracked.
2. At some point we're going to want to see metrics around "1000 badges distributed, 500 claimed"
3. Once a claim code has been distributed, don't allow someone to accidentally get the claim code.

**Comment by iamjessklein** [comment]
So I suspect that we are talking about printing out 10 claim codes on a standard 8.5 x 11 piece of paper?

**Comment by cmcavoy** [comment]
Yeah, but it doesn't need to be printing science...just do your best. If things don't align perfectly...no worries. The librarians can use scissors like champions!

**Comment by iamjessklein** [comment]
How about something like this:

![claimcodes](https://f.cloud.github.com/assets/535012/605902/9acf178e-cd20-11e2-9fef-2917d0b785b3.jpg)

**Comment by toolness** [comment]
> Something to note:
> 1. These should be new claim codes, and should be marked as "distributed". Date of the creation should be tracked.
> 2. At some point we're going to want to see metrics around "1000 badges distributed, 500 claimed"
> 3. Once a claim code has been distributed, don't allow someone to accidentally get the claim code.

I think the best way to implement this kind of functionality is to add the notion of tagging (or even the singular tag/category) to the Claim schema. When a user creates a new batch of claim codes, they have the option to assign a tag/category name to all of them; perhaps it can be auto-created to use the current date if nothing is entered for this. This way, someone could e.g. call one batch of tags "mini-maker-faire-june" and another batch "saturday-hackjam" and easily filter by tag on the claim management page, gather stats about all the claim codes w/ a particular tag, print all claim codes that have a particular tag (and even re-print them if they lose the original). This kind of mechanism would both be easier to implement than marking claim codes as "distributed", and it would also be a lot more flexible, allowing people to do what's required for this ticket, as well as providing a general mechanism to make it easier to organize and manage tags.

Along with a tag/category field, just adding a `creationDate` field to the Claim schema that defaults to the current date/time would also allow us to track temporal things--perhaps even a `claimedOn` field that records when the badge was claimed would be useful.

**Comment by cmcavoy** [comment]
@toolness how long will this take to implement?

**Comment by iamjessklein** [comment]
@toolness in terms of the design, I assume this means that I need to add a tag field as well as a date field. Do you agree?

**Comment by toolness** [comment]
> in terms of the design, I assume this means that I need to add a tag field as well as a date field. Do you agree?

Hmm, I really only meant the concept to be useful for administration, where perhaps the header/footer of each printed page might contain the batch name, or perhaps each ticket might contain it in very small print somewhere obscure. I didn't intend for the batch name to actually be printed prominently on each individual ticket. Doing that would probably imply that users should be able to e.g. rename batches and other things, which we don't have enough time to do.

Also, printing a date prominently on each ticket would imply that the date is something relevant to the ticket holder, e.g. the date of the event that they receive the ticket at, but the date we're talking about here is just the date of creation of the claim code itself, also only useful for tracking purposes. Adding the kind of date (I think) you're implying would mean a whole different set of requirements.

**Comment by iamjessklein** [comment]
@toolness I agree about the date field.

**Comment by cmcavoy** [comment]
Just make sure we know when the claim code was created. For reports and
such.

On Thu, Jun 6, 2013 at 8:59 AM, iamjessklein notifications@github.comwrote:

> @toolness https://github.com/toolness I agree about the date field.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/184#issuecomment-19046728
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by toolness** [comment]
Yep, we're recording that now... do we also want to record when it was claimed?

**Comment by cmcavoy** [comment]
Yeah, we should record when the badge is claimed. If that's not the case,
please ticket it... ;)

On Thu, Jun 6, 2013 at 10:34 AM, Atul Varma notifications@github.comwrote:

> Yep, we're recording that now... do we also want to record when it was
> claimed?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/184#issuecomment-19053553
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by toolness** [comment]
Ok, this doesn't look nearly as awesome as Jess' mockups yet, but it's got all the right info on it. Can Dr. Ballard give it some CSS love?

![screen shot 2013-06-06 at 3 50 15 pm](https://f.cloud.github.com/assets/124687/620366/7a8d9586-cee2-11e2-828d-280d256c1b0f.png)

I tried PDF print previews on Firefox, Chrome, and Safari, and they all appear to paginate it fine, without cutting things off or anything weird like that. Each claim code card is designed to be 2 inches wide and at least 3 inches tall (it can be taller if the text needs it to be). That can be changed in the CSS, of course.

Also note that the `OPENBADGER_CLAIM_URL_TEXT` environment variable must be defined in order for the handouts to have a URL on them; otherwise they just say "go to the website" rather than e.g. "go to csol.org/claim".

**Comment by threeqube** [comment]
we're trying to procure chi-sol.org or csol.me fyi.
