### ISSUE TITLE
Pagination: Prefer pagination at the bottom of the page

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#193]
After scrolling through all the issuers on page 1, I want to go to the next page, but have to scroll back up again to do so. 

![pages](https://dsz91cxz97a03.cloudfront.net/Lbq31ppMfd-1200x1200.jpeg)

It'd be great to have either pagination on the bottom or both top and bottom.

**Comment by iamjessklein** [comment]
:+1:  agreed

**Comment by brianloveswords** [comment]
IF YOU GIVE A MOUSE A COOKIE...
