### ISSUE TITLE
Add an env variable for a limited JWT

### ISSUE THREAD

**Issue by brianloveswords** [mozilla/openbadger#210]
We need to have the concept of a limited JWT token which will allow access to certain API endpoints but not others.

I propose we do this:
- Add an env variable for a limited JWT secret
- Add a flag in the auth middleware, maybe something like `req.limitedAccess = true` when an authentication is made with a limited JWT.

@toolness can you handle this if you get a chance?

**Comment by toolness** [comment]
This ticket disgusts me.

**Comment by cmcavoy** [comment]
@toolness wish your commit was a PR. Not sure if this is the right approach. Also, this isn't a 1.0 thing if we need more time. I want to do this right, as it's a crazy big change. We need some sort of API protection by late next week. Specifically, we want to limit iRemix to only issue the badges they own, and only see the badges of certain users. It's a tricky request. I can explain more. /cc @rl
