### ISSUE TITLE
Enable bulk deleting of claim codes

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#232]
Currently, org can only delete claim codes one by one. If you need to delete a bunch of claim codes, it's pretty pretty painful.

**Comment by brianloveswords** [comment]
Mixed feelings. Can I get a use case for deleting a ton of claim codes? Claim codes should not be deleted willy nilly, especially once they've been distributed.

**Comment by threeqube** [comment]
I hear you. My use case may be a unique one. 

I simply went in and created a bunch of claim codes for an org, to test claim code generation. I guess I should've done this in staging. Will close.
