### ISSUE TITLE
Add instructions to issuing interface.

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#235]
Need copy for the following answers to questions that came up yesterday in training, need to be concise enough to fit in the interface nicely:
1. What if a parent has multiple kids they're supplying their email address for? Put the parents email address in the interface once for each kid, they'll get multiple emails, each with a unique claim link.
2. General instructions on how it works
3. How to use the claim code interface

**Comment by threeqube** [comment]
I can help with this @emgollie

**Comment by emgollie** [comment]
Thoughts, @threeqube @cmcavoy?

QUESTION: What if I am responsible for more than one child?
If you're the parent or guardian to more than one child who is participating in the Chicago Summer of Learning, each of them should list your email address through their account. You will receive emails around badge review. These emails will include unique claim links for each child, so there's no need to worry that messages about one's badges will be confused with another.

QUESTION: How does this work?
(@threeqube, can we dicsuss what is needed here please?)

QUESTION: How do claim codes work? (via https://github.com/mozilla/CSOL-site/issues/205)
To claim the badge you've earned, enter the "claim code" written on the paper badge you received from your teacher, counselor or mentor.

Then hit the "Claim This Badge" button on your screen. Once you do this, the badge will be added to your My Badges page and you can throw the piece of paper away (or, better yet, recycle it!).

**Comment by threeqube** [comment]
> QUESTION: How does this work? (@threeqube, can we dicsuss what is needed here please?)

I think we need @cmcavoy's help on this. 

Also @cmcavoy, where should these instructional questions go?
