### ISSUE TITLE
Add search to API

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#236]
It hasn't been ticketed out in CSOL yet, but I'm positive a request for a search box in the /earn and /explore (badges and programs) is coming. We'll need an API endpoint.

**Comment by brianloveswords** [comment]
To confirm, we want to add a `search` param to `/v2/programs` and `/v2/badges`, correct? Should the API endpoints also deal with limiting and pagination?

**Comment by cmcavoy** [comment]
Yes - provide all the same features the filters have.

On Mon, Jun 17, 2013 at 3:02 PM, Brian J Brennan
notifications@github.comwrote:

> To confirm, we want to add a search param to /v2/programs and /v2/badges,
> correct? Should the API endpoints also deal with limiting and pagination?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/236#issuecomment-19570688
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com
