### ISSUE TITLE
"List in APIs" checkbox is not working

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#245]
CSOL has DYN badges listed in /earn but we've specifically unmarked the "List in APIs" checkbox for these so that these badges are not listed in API calls. However, they are being called and are showing up on the CSOL site as part of badges that are earnable when they are not. 

Need to be fixed as part of P1 I believe.

**Comment by brianloveswords** [comment]
Hmm, I'm having a hard time reproducing this. I added a test to ensure `doNotList` badges did not appear in the api (780a5c7797f5fdf24789170e0572bfddb9d1d8), and I also tried the following manual test:
1. Hit /v2/programs, note the first badge (`spanish-language-exploration`)
2. Go to /admin/badge/spanish-language-exploration, uncheck "List In APIs" and save.
3. Refresh /v2/programs, observe that `spanish-language-exploration` no longer appears.
4. Re-check "List in APIs"
   5 Refresh /v2/programs, observe that `spanish-language-exploration` badge once again appears.

@threeqube if you could provide any more information that would be helpful. @cmcavoy, feel free to explore this issue some more.

**Comment by cmcavoy** [comment]
From production, `https://badge.chicagosummeroflearning.org/v2/program/the-creativity-labs--indiana-university-digital-youth-network-dyn` [here](https://badge.chicagosummeroflearning.org/v2/program/the-creativity-labs--indiana-university-digital-youth-network-dyn) 

Lists `multimedia-experience-design` but that one is marked as "do not show in api":

`https://badge.chicagosummeroflearning.org/admin/badge/multimedia-experience-design/edit` [here](https://badge.chicagosummeroflearning.org/admin/badge/multimedia-experience-design/edit)

**Comment by brianloveswords** [comment]
Ah ha, that's a different endpoint. I'll check that out.
