### ISSUE TITLE
Implement copy updates to New Badge page

### ISSUE THREAD

**Issue by emgollie** [mozilla/openbadger#247]
Copy updates to https://openbadger-csol.mofostaging.net/admin/badge (cc @threeqube @iamjessklein):

Program
The name of the program that this badge is associated with.

Name
Start typing a descriptive name for your badge that is also fun.

Description 
A description of your badge will appear in each assertion created from this badge.

Criteria
The criteria text for the badge explains what someone has to do earn it. This can be prepared in markdown but should be kept simple. You can avoid markup by using backticks: `<strong>`

Tags
Tags describe the badge and area of interest. Separate tags with commas. 

Time Commitment to Earn

Age Range
(Remove control key text as earner will only fall into one category. Add 24+ as option.)

List in APIs 
This determines whether a badge should be shown when an API call is made to pull a list of all badges earned. In most cases, this should be left checked.

New Image 
The graphics and visuals that represents the badge.

STEAM Badging Details
This is a special STEAM badge award for ____. If you're uncertain about what to enter in this field, leave it set to Nothing.

This badge contributes points towards special STEAM badges in… 
Hold down the Control key (or Command key on Macs) to select multiple options. 

STEAM Badge Point Contribution 
This is the number of points earning this badge contributes to earning a special STEAM badge in any of its categories. (@chloeatplay, where can we find these point values/associations?)

**Comment by threeqube** [comment]
Point values are as follows:

Participation = 0
Skill = 1
Achievement = 2
Getting 3 points in same STEAM category unlocks city level badge. 

I find this field to be redundant. There's another field above where you specify whether the badge is P, S, or A. Feels like the points should be automatically attributed based on the value inputted there.

**Comment by chloeatplay** [comment]
Hey @ all - strongly strongy urge NOT to mention any points in the official copy. We decided this way back and IMHO it is a terrible gamification precedent, plus mentioning that you gain _0, or 1 points_ really doesn't work from a point-design view. @carlacasilli  can say more about why this should not be in the copy. That is why we made the illustrations ;)

**Comment by threeqube** [comment]
@chloeatplay completely agree. This is the open badger admin panel though and NOT learner/user facing.

**Comment by chloeatplay** [comment]
:confounded: sorry then! I blame reading this after a full day at a conference. :collision:

**Comment by threeqube** [comment]
All good. :smiley:

**Comment by carlacasilli** [comment]
I'm glad to know that @chloeatplay, you're fighting the anti-point fight (that I'm fighting on another front). :+1:  :zap:  But I think we're all good. :smile:
