### ISSUE TITLE
On program page, add ability to select organization under which it falls similar to how a badge edit page allows select program

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#250]
Currently, the program detail page does not allow movement among organizations. If we can have a dropdown similar to the bade detail page that allows for a dropdown of program selection, that would be radical. 

This is a problem particularly with CSOL in that orgs are now coming back to us requesting that they consolidate programs so I need to move programs around or delete them.

**Comment by marihuertas** [comment]
cc @cmcavoy – this relates to ticket https://chicagosummeroflearning.zendesk.com/agent/#/tickets/6 in Zendesk, and CPL asked about this specifically in a meeting last week. What is our course forward?

**Comment by cmcavoy** [comment]
We can fix these by deleting and moving. It's just inconvenient. Brian has been on other things (also CPL related, boosting the email capacity). I think we move forward with the less convenient fix for now.

**Comment by brianloveswords** [comment]
@cmcavoy doing that might break things – badges are associated with programs by program id, so that would orphan all badges related to that program if you deleted it.

**Comment by brianloveswords** [comment]
I SHOULD HAVE ALSO MENTIONED that I am going to work on this today. I should have it done by tomorrow if everything goes smoothly.

**Comment by threeqube** [comment]
:+1:

**Comment by marihuertas** [comment]
Perrrrrrrfect. Thanks guys.

**Comment by brianloveswords** [comment]
NOTICE: things are not going smoothly, we are held up deploying the previous issue I was working.

**Comment by marihuertas** [comment]
Thanks for the heads-up, @brianloveswords – give me a shout when you hammer out the kinks.

**Comment by marihuertas** [comment]
Hey @brianloveswords + @cmcavoy – giving this a morning bump to see how things are shaking out. Can we touch base on this today / tomorrow (Tuesday, 7/9)? This work will help resolve a few queries in Zendesk, so I want to get a feel for how it's progressing this week.

**Comment by brianloveswords** [comment]
Branch `250-change-program-organization` has been made and I am working on it as we <del>speak</del> <ins>type at each other through the internet</ins>.

**Comment by marihuertas** [comment]
@brianloveswords :: I love when people are working on things even as they are typing at each other through the internet. :) Do you think end of week is good for delivery date to stakeholders?

**Comment by brianloveswords** [comment]
@marihuertas definitely (I will likely have it done in code by tomorrow, but staging and deploying to prod will take a little longer of course)

**Comment by marihuertas** [comment]
Badass! Thanks @brianloveswords!
