### ISSUE TITLE
Recommend only online badges

### ISSUE THREAD

**Issue by erinknight** [mozilla/openbadger#252]
For CSOL - the recommendation system should only suggest badges that are categorized as 'online'.

**Comment by brianloveswords** [comment]
That is way less complicated than it sounded on the call this morning, but then again I was also still 95% asleep.

**Comment by brianloveswords** [comment]
@erinknight ALSO, when you say "only" do mean even if there are no online skill badges to recommend (as in, if they've completed all of the STEAM badges, we would not recommend them anything?)

**Comment by threeqube** [comment]
We are dealing with this case with copy treatment as per https://github.com/mozilla/openbadger/pull/253#issuecomment-19827559
