### ISSUE TITLE
Remove character limits for badge titles.

### ISSUE THREAD

**Issue by marihuertas** [mozilla/openbadger#271]
I'm adding badges for a new org and hit an error when I added a badge with a long name. Can we remove the character limit?

Not super pressing, but minorly annoying when I'm trying to add in a bunch of new badges.

![screen shot 2013-07-10 at 11 05 57 pm](https://f.cloud.github.com/assets/1434869/779583/3fd9bdb2-e9df-11e2-98ba-ad0c3f8bb2c2.png)

**Comment by marihuertas** [comment]
Hmm. Just tried to shorten the badge name and I'm having the same issue when I try to upload it. Thoughts, @brianloveswords ... ?

**Comment by threeqube** [comment]
Realized these images are a .jpg. I'm fairly certain, open badger only accepts .png image fils. Let us investigate further.

**Comment by brianloveswords** [comment]
That error message is saying "your image is too big". There's a max size
for the images (either 256k or 128k).

Brian

**Comment by marihuertas** [comment]
Hey @threeqube – yeah, they were .jpgs but I changed them to .png files and that error still popped up.

@brianloveswords – I'll downsize the images and try again. Thanks!
