### ISSUE TITLE
Add ability for issuer to add a badge to their organization

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#292]
Issuer users should be able to add badge classes and programs to their organization.

**Comment by cmcavoy** [comment]
Actually, it's probably easier (for now) to allow admin's it issue a badge.

Currently,
_Admins can_
- create organizations
- create programs
- create badge classes
- create claim codes

_Issuers can_
- create claim codes
- issue badges to an email address

We need a user that can
- create badge instances
- create programs
- create claim codes (including multi-use codes)
- issue badges to an email address

**Comment by brianloveswords** [comment]
So to confirm, I should probably just allow admins to issue any badges for any orgs (note: this is something that makes sense anyway).

**Comment by cmcavoy** [comment]
Yes, :thumbsup:

On Wed, Sep 18, 2013 at 11:14 AM, Brian J Brennan
notifications@github.comwrote:

> So to confirm, I should probably just allow admins to issue any badges for
> any orgs (note: this is something that makes sense anyway).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/292#issuecomment-24677684
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by threeqube** [comment]
:+1:

**Comment by brianloveswords** [comment]
Okay, so I'm looking at this now – it appears to be done already? If I login as an admin and go to `/issue` I can issue badges. So I guess the task could be to add a link in the UI for issuing?

**Comment by cmcavoy** [comment]
Can you add it to the menu drop down per badge on /admin?
