### ISSUE TITLE
Claim badges interface: Add instructions on how manual generation works

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#296]

**Comment by brianloveswords** [comment]
What sort of instructions? (cc @cmcavoy)

**Comment by threeqube** [comment]
What are the requirements for the claim code that the staff can generate? all lower case, punctured with hyphens, alphanumerical, etc?

**Comment by brianloveswords** [comment]
There are no rules. ANARCHY!

But for real, they can really put in anything. I guess we should just tell them to not use spaces and that they should be universally unique.

**Comment by threeqube** [comment]
Can we add something to that effect text wise on the interfacr or do you want me to handle that separately when training?
