### ISSUE TITLE
Claim codes interface: Obscure bulk actions 

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#297]
Not needed for CEM

**Comment by brianloveswords** [comment]
@threeqube Can you give me a screenshot of what should be removed? I don't think I understand what I'm supposed to do for this ticket.

**Comment by threeqube** [comment]
Do you see where it says bulk badges at the far bottom? We need to get rid of that. 

![screen shot 2013-09-23 at 2 31 53 pm](https://f.cloud.github.com/assets/1424627/1194030/824c93b6-247e-11e3-8dc1-a51674db734e.png)

**Comment by brianloveswords** [comment]
Ah, so I was partially confused by the title – "claim badges interface" vs "claim _codes_ interface". Also that doesn't show up unless there are existing codes, and I was looking at a badge that had no codes. GOT IT NOW.

**Comment by threeqube** [comment]
Ma bad. I'll update the ticket title. SOUNDS GOOD.
