### ISSUE TITLE
Response time lag is pretty significant

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#298]
Response time seems pretty laggy. 

Load time for almost everything, hitting back home, next page, new badge all seem to take a few seconds.

**Comment by cmcavoy** [comment]
What instance were you using? CSOL prod?

On Thu, Sep 19, 2013 at 7:17 PM, threeqube notifications@github.com wrote:

> Response time seems pretty laggy.
> 
> Load time for almost everything, hitting back home, next page, new badge
> all seem to take a few seconds.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/298
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by threeqube** [comment]
@cmcavoy yep CSOL prod.
