### ISSUE TITLE
Criteria page has webmaker text artifact that should be removed 

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#309]
If you look at this http://badger.connectededucators.org/badge/criteria/kickoff-event-cem-opening-celebrationgala

It has a weird Webmaker badges text artifact that should be deleted since this is a CEM criteria page. 

![screen shot 2013-10-10 at 3 21 45 pm](https://f.cloud.github.com/assets/1424627/1310878/720108e6-31fa-11e3-9bcb-aa250ac728f7.png)

**Comment by ghost** [comment]
Addressed by #310.

**Comment by cmcavoy** [comment]
pushed to prod and confirmed
