### ISSUE TITLE
Badges not displaying

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/openbadger#332]
Not sure if this is the best place to put this, but I noticed that my Open Badges-related community badges weren't showing up in my [blog](https://dougbelshaw.com/blog) sidebar... 

![No badges :(](http://i.imgur.com/ZZfCwMU.png)

Even the [URLs](http://badger.openbadges.org/badge/criteria/foob-friend-of-open-badges) don't seem to resolve...

![Dead badger](http://i.imgur.com/79Tl2IZ.png)

**Comment by threeqube** [comment]
cc/ @cmcavoy

**Comment by cmcavoy** [comment]
The Redis instance on Heroku changed locations, but OpenBadger didn't update the config. Opening a ticket to handle that. In the meantime, this is fixed. Thanks @dajbelshaw !
