### ISSUE TITLE
Landing page at `GET /` instead of admin login

### ISSUE THREAD

**Issue by brianloveswords** [mozilla/openbadger#34]
Going to https://badges.webmaker.org should give you some sort of information rather than the admin login screen.

@carlacasilli, @cmcavoy, this is kinda important and it totally slipped my mind. People will probably end up typing in https://badges.webmaker.org at some point and we have nothing to show them. Obviously a post-mozfest thing since we have no content, but something we should plan for.

**Comment by LeoMcA** [comment]
Unless I'm mistaken, this issue is now fixed. Shouldn't it be closed?

**Comment by brianloveswords** [comment]
It is indeed, thanks @LeoMcA
