### ISSUE TITLE
Add left padding to info block on show-badge page

### ISSUE THREAD

**Issue by brianloveswords** [mozilla/openbadger#37]
That badge image is floating left, so whatever the width of that float is, use that much padding

![Imgur](http://i.imgur.com/0zoco.png)

**Comment by stenington** [comment]
Alternatively you can use this funky [media block](http://www.stubbornella.org/content/2010/06/25/the-media-object-saves-hundreds-of-lines-of-code/) technique. It's a pretty simple pattern that ends up being useful EVERYWHERE!

**Comment by brianloveswords** [comment]
PATCHES WELCOME :trollface:

**Comment by brianloveswords** [comment]
GitHub needs :dealwithit: animated emoji.

**Comment by stenington** [comment]
[PATCHES](http://www.facebook.com/pages/Patches-the-cat/179739115398499) IS ALWAYS WELCOME!

<img src="http://profile.ak.fbcdn.net/hprofile-ak-prn1/162019_179739115398499_4776535_n.jpg">
