### ISSUE TITLE
Gather month to month badges issued data

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#55]
Using the handy dandy field, https://github.com/mozilla/openbadger/blob/development/models/badge-instance.js#L30

NOTE: this one is due Monday morning for Board slides. Word up.

**Comment by cmcavoy** [comment]
started messing with this a bit in https://github.com/cmcavoy/openbadger/tree/55-monthly but am a bit baffled by https://github.com/cmcavoy/openbadger/blob/55-monthly/app.js#L74 Not sure if the work in my branch is helpful, as you're super fast at things. BUT, if it is, have at it.

**Comment by rossbruniges** [comment]
If the ultimate goal is to feed this information into geckoboard I found
they have some nice looking api libraries that can easily provide us this
data too.
