### ISSUE TITLE
Allow multiple organizations to use a single instance of Open Badger

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#57]
All badges currently come from a single organization. Need to update the model to allow badges to come from different organizations.

**Comment by paulsmith** [comment]
So this should probably land in two parts: first, the create and update bits of badges are modified to take an issuer as an argument (a `<select>` in the chrome, `<option>`s iterate over a list of issuers which will just be one to start). Second, the admin is updated to list, create new, update existing, and delete (maybe?) issuers.

The maybe? regarding delete is what happens to an orphaned badge (i.e., does the delete cascade, or is the foreign key ref null). But that can be dealt with in a future issue/PR.

**Comment by cmcavoy** [comment]
> So this should probably land in two parts: first, the create and update bits of badges are modified to take an issuer as an argument (a <select> in the chrome, <option>s iterate over a list of issuers which will just be one to start). Second, the admin is updated to list, create new, update existing, and delete (maybe?) issuers.

Sounds good to me. If you haven't seen it, you can add to-do lists to these tickets now with the convenient `- [ ] this is a to-do` format, which yields,
- [ ] this is a to-do

Which seems appropriate for the above.

> The maybe? regarding delete is what happens to an orphaned badge (i.e., does the delete cascade, or is the foreign key ref null). But that can be dealt with in a future issue/PR.

I like cascading deletes, where the deletes are actually just records marked as deleted, so they're easy to recover. But yes, belongs in a future issue.

**Comment by paulsmith** [comment]
- [x] modify Issuer schema to include a list of badges
- [x] modify Badge schema to require an Issuer
- [x] update badge create/update app views to include issuer as a form field, database writes as appropriate
- [x] add shortName property to issuer, for URLs
- [x] add issuer list, create, and update views in the admin
- [x] make sure initial login flow still works and redirects to creating first issuer (instead of "configure" semantics)

**Comment by paulsmith** [comment]
Should the Issuer schema have an analogous `badges: [Badge.schema]`?

**Comment by paulsmith** [comment]
I feel like this branch/pull is in pretty good shape, time for some other eyeballs on it.
