### ISSUE TITLE
Some badges shouldn't be returned in the all badges API

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#77]
Some badges (like the iRemix challenge badges) shouldn't be listed on the CSOL badges page. We _could_ filter on the CSOL side, or in the [API](https://github.com/mozilla/openbadger/wiki/APIv2#get-v2badges).

The simplest possible implementation is to include a 'exclude_from_listing' flag on badge definitions, or CSOL could filter out badges from particular orgs.

**Comment by brianloveswords** [comment]
Closed by 2e70166378c70c5233babbe4e51f9af77fdd1ee6
