### ISSUE TITLE
Multi use claim codes

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#83]
Create a badge that allows multiple claims on a single claim code. i.e 'kite-festival'.

**Comment by brianloveswords** [comment]
To be clear on the requirement:
- These will be claim codes than can be used infinite times, and
- They do not expire.

In a sentence, everyone will be able to use `kite-festival` for the Kite Festival badge until the end of time, versus 300 people can use `kite-festival` until June 30th.

**Comment by threeqube** [comment]
Relevant wireframe is as follows:

![claimcode](https://f.cloud.github.com/assets/535012/425428/1a246c00-adaf-11e2-90c8-2a39e6990dc8.png)

**Comment by iamjessklein** [comment]
Does the actual claim code need to be designed? Like a template?

**Comment by threeqube** [comment]
@iamjessklein good point. Not for this particular kind of claim code though. This is more a unique url that generates claim codes so we're just providing the city with the urls that they can include on any of their print material for each of the events. However, we should think about it for regular claim codes https://github.com/mozilla/CSOL-site/issues/93 I think @cmcavoy wants to keep this as simple as possible to lower printing logistics and cost.

**Comment by brianloveswords** [comment]
Closed by 9589f3557d41dc63f2e69f2f73200c507745cdaf
