### ISSUE TITLE
Additional Recommendation logic

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#86]
Good notes in mozilla/csol-site#171
- Bias of online over programs
- don't recommend anything that the time has expired
- make recommendations on what they already have...so if someone has an S badge, don't recommend more S stuff.

**Comment by brianloveswords** [comment]
Basic implementation done, closing for now. We can either re-open this ticket or open a new one if the implementation needs to get more advanced.

**Comment by cmcavoy** [comment]
- Bias of online over programs
- don't recommend anything that the time has expired
- make recommendations on what they already have...so if someone has an S badge, don't recommend more S stuff.

**Comment by carlacasilli** [comment]
@cmcavoy Q: where do you want the recommendation aspect to go, in this ticket?

Ex:
If a badge represents STE, show S, T, E badges; make up the remaining two recommended next step badges randomly with S, T, E category badges.

**Comment by cmcavoy** [comment]
@ccasilli work on it offline, then talk to me and i'll put it in this
ticket.

On Tue, May 28, 2013 at 3:44 PM, Carla Casilli notifications@github.comwrote:

> @cmcavoy https://github.com/cmcavoy Q: where do you want the
> recommendation aspect to go, in this ticket?
> 
> Ex:
> If a badge represents STE, show S, T, E badges; make up the remaining two
> recommended next step badges randomly with S, T, E category badges.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/86#issuecomment-18578713
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com
