### ISSUE TITLE
Some badges are awarded when conditions are met

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#90]
Related to CSOL STEAM badges, and the first badge / CSOL participation badge. I think we can use the existing trigger / behavior system, but because the triggering would happen inside of OpenBadger, we probably need some changes.

**Comment by threeqube** [comment]
In addition to the participation badge, these badges are also auto-triggered: https://github.com/mozilla/CSOL-site/issues/50

**Comment by cmcavoy** [comment]
For the STEAM badges, each prerequisite badge will count for either 1/2 or 1 'point' against the related STEAM category badge. When a user earns the requisite number of points, they'll be awarded the STEAM badge. They'll get a notification in CSOL, and an email.

**Comment by threeqube** [comment]
To add to @cmcavoy, there are 3 types of badges; PARTICIPATION, SKILL and ACHIEVEMENT and each badge in the system is notated of their type. 

In order to earn a Scientist badge, one must earn 3 Science SKILL badges.  
1 ACHIEVEMENT badge is == 2 SKILL badges. 
PARTICIPATION badges do not count towards a skill or achievement.

**Comment by cmcavoy** [comment]
I think we're going to assign point values to badges...or something. I was
probably diving into implementation there, but we're basically saying the
same thing. Some badges are 0, some are 1/2, some are 1. Or, some are 0,
some are 1, some are 2.

On Tue, May 14, 2013 at 10:40 AM, threeqube notifications@github.comwrote:

> To add to @cmcavoy https://github.com/cmcavoy, there are 3 types of
> badges; PARTICIPATION, SKILL and ACHIEVEMENT and each badge in the system
> is notated of their type.
> 
> In order to earn a Scientist badge, one must earn 3 Science SKILL badges.
> 
> 1 ACHIEVEMENT badge is == 2 SKILL badges.
> PARTICIPATION badges do not count towards a skill or achievement.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/90#issuecomment-17884404
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by threeqube** [comment]
Got it. 

Participation: 0
Skill: 1
Achievement: 2

Need 3 total points in same STEAM theme to earn a S, T, E, A, M badge.

**Comment by cmcavoy** [comment]
closing this, final work is in #126.
