### ISSUE TITLE
Implement "get badge info by claim code" API endpoint

### ISSUE THREAD

**Issue by brianloveswords** [mozilla/openbadger#93]
We need this to implement issue #78, and the related CSOL-site bits: CSOL is going to need to query OpenBadger about a badge only based on the claim code once we send a user over there to claim the badge.

**Comment by stenington** [comment]
Not super urgent, I guess, but having this will allow CSOL to display more info about the badge a user is potentially about to claim.

**Comment by cmcavoy** [comment]
@toolness this is probably something you can implement quickly if it helps
@mlarsson

On Tue, May 28, 2013 at 10:11 AM, Mike Larsson notifications@github.comwrote:

> Not super urgent, I guess, but having this will allow CSOL to display more
> info about the badge a user is potentially about to claim.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/93#issuecomment-18556940
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com
